# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ian/VSCODE/C++/Fourier Picture"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ian/VSCODE/C++/Fourier Picture/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ian/VSCODE/C++/Fourier Picture/build/CMakeFiles" "/home/ian/VSCODE/C++/Fourier Picture/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ian/VSCODE/C++/Fourier Picture/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dft

# Build rule for target.
dft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dft
.PHONY : dft

# fast build rule for target.
dft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dft.dir/build.make CMakeFiles/dft.dir/build
.PHONY : dft/fast

#=============================================================================
# Target rules for targets named draw

# Build rule for target.
draw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 draw
.PHONY : draw

# fast build rule for target.
draw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/draw.dir/build.make CMakeFiles/draw.dir/build
.PHONY : draw/fast

#=============================================================================
# Target rules for targets named fourier_draw

# Build rule for target.
fourier_draw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fourier_draw
.PHONY : fourier_draw

# fast build rule for target.
fourier_draw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourier_draw.dir/build.make CMakeFiles/fourier_draw.dir/build
.PHONY : fourier_draw/fast

#=============================================================================
# Target rules for targets named kissfft

# Build rule for target.
kissfft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kissfft
.PHONY : kissfft

# fast build rule for target.
kissfft/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/CMakeFiles/kissfft.dir/build.make _deps/kissfft-build/CMakeFiles/kissfft.dir/build
.PHONY : kissfft/fast

#=============================================================================
# Target rules for targets named fastconvr

# Build rule for target.
fastconvr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastconvr
.PHONY : fastconvr

# fast build rule for target.
fastconvr/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/tools/CMakeFiles/fastconvr.dir/build.make _deps/kissfft-build/tools/CMakeFiles/fastconvr.dir/build
.PHONY : fastconvr/fast

#=============================================================================
# Target rules for targets named fastconv

# Build rule for target.
fastconv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastconv
.PHONY : fastconv

# fast build rule for target.
fastconv/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/tools/CMakeFiles/fastconv.dir/build.make _deps/kissfft-build/tools/CMakeFiles/fastconv.dir/build
.PHONY : fastconv/fast

#=============================================================================
# Target rules for targets named fft

# Build rule for target.
fft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fft
.PHONY : fft

# fast build rule for target.
fft/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/tools/CMakeFiles/fft.dir/build.make _deps/kissfft-build/tools/CMakeFiles/fft.dir/build
.PHONY : fft/fast

#=============================================================================
# Target rules for targets named psdpng

# Build rule for target.
psdpng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psdpng
.PHONY : psdpng

# fast build rule for target.
psdpng/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/tools/CMakeFiles/psdpng.dir/build.make _deps/kissfft-build/tools/CMakeFiles/psdpng.dir/build
.PHONY : psdpng/fast

#=============================================================================
# Target rules for targets named fastfilt

# Build rule for target.
fastfilt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastfilt
.PHONY : fastfilt

# fast build rule for target.
fastfilt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/fastfilt.dir/build.make _deps/kissfft-build/test/CMakeFiles/fastfilt.dir/build
.PHONY : fastfilt/fast

#=============================================================================
# Target rules for targets named bm_kiss

# Build rule for target.
bm_kiss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bm_kiss
.PHONY : bm_kiss

# fast build rule for target.
bm_kiss/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/bm_kiss.dir/build.make _deps/kissfft-build/test/CMakeFiles/bm_kiss.dir/build
.PHONY : bm_kiss/fast

#=============================================================================
# Target rules for targets named bm_fftw

# Build rule for target.
bm_fftw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bm_fftw
.PHONY : bm_fftw

# fast build rule for target.
bm_fftw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/bm_fftw.dir/build.make _deps/kissfft-build/test/CMakeFiles/bm_fftw.dir/build
.PHONY : bm_fftw/fast

#=============================================================================
# Target rules for targets named st

# Build rule for target.
st: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 st
.PHONY : st

# fast build rule for target.
st/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/st.dir/build.make _deps/kissfft-build/test/CMakeFiles/st.dir/build
.PHONY : st/fast

#=============================================================================
# Target rules for targets named tkfc

# Build rule for target.
tkfc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tkfc
.PHONY : tkfc

# fast build rule for target.
tkfc/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/tkfc.dir/build.make _deps/kissfft-build/test/CMakeFiles/tkfc.dir/build
.PHONY : tkfc/fast

#=============================================================================
# Target rules for targets named ffr

# Build rule for target.
ffr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffr
.PHONY : ffr

# fast build rule for target.
ffr/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/ffr.dir/build.make _deps/kissfft-build/test/CMakeFiles/ffr.dir/build
.PHONY : ffr/fast

#=============================================================================
# Target rules for targets named tr

# Build rule for target.
tr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tr
.PHONY : tr

# fast build rule for target.
tr/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/tr.dir/build.make _deps/kissfft-build/test/CMakeFiles/tr.dir/build
.PHONY : tr/fast

#=============================================================================
# Target rules for targets named testcpp

# Build rule for target.
testcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testcpp
.PHONY : testcpp

# fast build rule for target.
testcpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/kissfft-build/test/CMakeFiles/testcpp.dir/build.make _deps/kissfft-build/test/CMakeFiles/testcpp.dir/build
.PHONY : testcpp/fast

src/dft.o: src/dft.cpp.o
.PHONY : src/dft.o

# target to build an object file
src/dft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dft.dir/build.make CMakeFiles/dft.dir/src/dft.cpp.o
.PHONY : src/dft.cpp.o

src/dft.i: src/dft.cpp.i
.PHONY : src/dft.i

# target to preprocess a source file
src/dft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dft.dir/build.make CMakeFiles/dft.dir/src/dft.cpp.i
.PHONY : src/dft.cpp.i

src/dft.s: src/dft.cpp.s
.PHONY : src/dft.s

# target to generate assembly for a file
src/dft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dft.dir/build.make CMakeFiles/dft.dir/src/dft.cpp.s
.PHONY : src/dft.cpp.s

src/draw.o: src/draw.cpp.o
.PHONY : src/draw.o

# target to build an object file
src/draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/draw.dir/build.make CMakeFiles/draw.dir/src/draw.cpp.o
.PHONY : src/draw.cpp.o

src/draw.i: src/draw.cpp.i
.PHONY : src/draw.i

# target to preprocess a source file
src/draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/draw.dir/build.make CMakeFiles/draw.dir/src/draw.cpp.i
.PHONY : src/draw.cpp.i

src/draw.s: src/draw.cpp.s
.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/draw.dir/build.make CMakeFiles/draw.dir/src/draw.cpp.s
.PHONY : src/draw.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourier_draw.dir/build.make CMakeFiles/fourier_draw.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourier_draw.dir/build.make CMakeFiles/fourier_draw.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourier_draw.dir/build.make CMakeFiles/fourier_draw.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... bm_fftw"
	@echo "... bm_kiss"
	@echo "... dft"
	@echo "... draw"
	@echo "... fastconv"
	@echo "... fastconvr"
	@echo "... fastfilt"
	@echo "... ffr"
	@echo "... fft"
	@echo "... fourier_draw"
	@echo "... kissfft"
	@echo "... psdpng"
	@echo "... st"
	@echo "... testcpp"
	@echo "... tkfc"
	@echo "... tr"
	@echo "... src/dft.o"
	@echo "... src/dft.i"
	@echo "... src/dft.s"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

